apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
images:
  - name: ghcr.io/markrushb/automation-hub/camp-monitor
    newTag: e693f47b7ce5ef7b5cf3fce1684e8a3fd30a30bf

