apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s/deployment.yaml
configMapGenerator:
  - name: camp-monitor-config
    files:
      - config.json=config/config.json
  - name: camp-monitor-source
    files:
      - camp_monitor.py=camp_monitor.py

